[build]
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[functions]
  node_bundler = "esbuild"

# Regular Function 路由
[[redirects]]
  from = "/api/proxy"
  to = "/.netlify/functions/proxy"
  status = 200

# Edge Functions 已经通过 config.path 自动配置路由
# /edge-proxy -> 基础版本
# /edge-proxy-advanced -> 高级版本

[[headers]]
  for = "/api/proxy"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"

[[headers]]
  for = "/edge-proxy"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"

[[headers]]
  for = "/edge-proxy-advanced"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"